SET VERIFY OFF
SET LONG 100000
SET PAGESIZE 0 FEEDBACK OFF HEADING OFF
SET TRIMSPOOL ON
SET LINESIZE 200

-- &1 is the table name passed from the batch file
SELECT DBMS_METADATA.GET_DDL('TABLE', '&1') || ';' FROM DUAL;

EXIT;
