SET VERIFY OFF
SET LONG 2000000
SET PAGESIZE 0
SET FEEDBACK OFF
SET HEADING OFF
SET TRIMSPOOL ON
SET LINESIZE 32767

EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'CONSTRAINTS_AS_ALTER', true);
SELECT DBMS_METADATA.GET_DEPENDENT_DDL('CONSTRAINT', '&1') FROM DUAL;